# Generated by Django 3.2.6 on 2021-08-04 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rpsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameWon', models.CharField(choices=[('W', 'UserWon'), ('L', 'UserLost'), ('T', 'Tie')], max_length=1)),
                ('userThrow', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1)),
                ('computerThrow', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
